name: 🧪 Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Nim 2.2.0
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '2.2.0'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libpcre3-dev
      
      - name: Install dependencies
        run: nimble install -y --depsOnly
      
      - name: Run tests
        run: nimble test