name: 🧪 Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Nim 2.2.0
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '2.2.0'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install system dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libpcre3-dev build-essential
      
      - name: Install system dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          # macOS has build tools by default, just make sure we have them
          xcode-select --install 2>/dev/null || true
      
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      
      - name: Cache Y-CRDT build
        uses: actions/cache@v3
        with:
          path: |
            y-crdt
            lib
          key: ${{ runner.os }}-ycrdt-${{ hashFiles('**/Cargo.lock', 'setup_ycrdt.sh') }}
          restore-keys: |
            ${{ runner.os }}-ycrdt-
      
      - name: Build Y-CRDT library
        run: nimble build_ycrdt
      
      - name: Install dependencies
        run: nimble install -y --depsOnly
      
      - name: Run tests
        run: nimble test